# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
# Configuraci\u00f3n de conexi\u00f3n a Informix
DB_DRIVER=oracle.jdbc.driver.OracleDriver
DB_URL=jdbc:oracle:thin:@10.191.143.5:1525/vtct
DB_USER=TAE_NOTIFICA
DB_PASSWORD=keFa#h4PtUz7Hds$
#RUTA_CONF=/export/home/cem/.alex/NOTIFICASALDOSUSA/conf
#DB_DRIVER=oracle.jdbc.driver.OracleDriver
#DB_URL=jdbc:oracle:thin:@10.191.143.5:1525/vtct
#DB_USER=VI9C5E6
#DB_PASSWORD=GwxVzc}J1HdL_Ty54{GQk6T67
